version:3
services:
  api:
    build: .
    ports:
      - "5000:80"
    environment:
      - SECRET_KEY=b4m8po9ygfr99po56zsc7774zswvb78ff9d
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=60
      - DATABASE_URL=db
      - DATABASE_PORT=5432
      - DATABASE_NAME=fastapi
      - DATABASE_ROOT_USER=postgres
      - DATABASE_ROOT_PASSWORD=postgres

    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_DB: fastapi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: